namespace NoiraPlayer.Native
{
    enum NativePlaybackState
    {
        NativePlaybackState_Stopped = 0,
        NativePlaybackState_Opening = 1,
        NativePlaybackState_Buffering = 2,
        NativePlaybackState_Playing = 3,
        NativePlaybackState_Paused = 4,
        NativePlaybackState_Failed = 5
    };

    enum NativeHdrStatus
    {
        NativeHdrStatus_Unknown = 0,
        NativeHdrStatus_Unsupported = 1,
        NativeHdrStatus_Off = 2,
        NativeHdrStatus_On = 3,
        NativeHdrStatus_Failed = 4
    };

    runtimeclass NativePlaybackOpenRequest
    {
        NativePlaybackOpenRequest();
        String ItemId;
        String MediaSourceId;
        String DirectStreamUrl;
        Int64 StartPositionTicks;
        Int32 AudioStreamIndex;
        Boolean HasAudioStreamIndex;
        Int32 SubtitleStreamIndex;
        Boolean HasSubtitleStreamIndex;
        Double VideoFrameRate;
    }

    runtimeclass NativePlaybackStatus
    {
        NativePlaybackStatus();
        NativeHdrStatus HdrStatus;
        Boolean IsHdrDisplayAvailable;
        Boolean IsHdrOutputActive;
        Double RefreshRateHz;
        String Message;
        String SwapChainFormat;
        String SwapChainColorSpace;
        Boolean IsTenBitSwapChain;
        Boolean IsVideoProcessorColorSpaceValidated;
        String VideoProcessorInputColorSpace;
        String VideoProcessorOutputColorSpace;
        String VideoProcessorConversionStatus;
    }

    runtimeclass NativePlaybackQualityMetrics
    {
        NativePlaybackQualityMetrics();
        Boolean ObservedVideoSourceAvailable;
        String ObservedVideoCodec;
        UInt32 ObservedVideoWidth;
        UInt32 ObservedVideoHeight;
        Double ObservedVideoFrameRate;
        String ObservedVideoRange;
        String ObservedColorPrimaries;
        String ObservedColorTransfer;
        String ObservedColorSpace;
        String ObservedHdrKind;
        Boolean ObservedIsDolbyVision;
        UInt32 ObservedDolbyVisionProfile;
        UInt32 ObservedDolbyVisionCompatibilityId;
        Boolean ObservedHasHdr10BaseLayer;
        Boolean ObservedHasHlgBaseLayer;
        UInt64 RenderPasses;
        UInt64 DecodedVideoFrames;
        UInt64 HardwareDecodedVideoFrames;
        UInt64 SoftwareDecodedVideoFrames;
        UInt64 RenderedVideoFrames;
        UInt64 SubmittedAudioFrames;
        Int32 SelectedAudioStreamIndex;
        UInt64 SubtitleDecodedCueCount;
        UInt64 SubtitleCueRenderCount;
        Int32 SelectedSubtitleStreamIndex;
        UInt64 DroppedVideoFrames;
        UInt64 SeekPrerollDroppedFrames;
        UInt64 VideoAheadWaitCount;
        UInt64 AudioAheadWaitCount;
        UInt64 VideoClockWaitCount;
        UInt64 VideoStarvedPasses;
        UInt64 AudioStarvedPasses;
        UInt64 QueuedAudioBuffers;
        Int64 AudioClockTicks;
        Int64 VideoPositionTicks;
        Double NativeGraphOpenDurationMs;
        Double FfmpegOpenInputDurationMs;
        Double FfmpegStreamInfoDurationMs;
        Double NativeStartupSeekDurationMs;
        UInt64 FfmpegOpenInputBytesRead;
        UInt64 FfmpegStreamInfoBytesRead;
        UInt64 NativeStartupSeekBytesRead;
        UInt64 NativeFirstFrameTransportBytesRead;
        String StartupTransportProvider;
        Boolean StartupTransportCallEvidenceAvailable;
        String FfmpegOpenInputTransportProvider;
        Boolean FfmpegOpenInputTransportCallEvidenceAvailable;
        UInt64 FfmpegOpenInputTransportReadCalls;
        UInt64 FfmpegOpenInputTransportSeekCalls;
        Double FfmpegOpenInputTransportReadWaitMs;
        Double FfmpegOpenInputTransportSeekWaitMs;
        UInt64 FfmpegOpenInputTransportSeekDistanceBytes;
        String FfmpegStreamInfoTransportProvider;
        Boolean FfmpegStreamInfoTransportCallEvidenceAvailable;
        UInt64 FfmpegStreamInfoTransportReadCalls;
        UInt64 FfmpegStreamInfoTransportSeekCalls;
        Double FfmpegStreamInfoTransportReadWaitMs;
        Double FfmpegStreamInfoTransportSeekWaitMs;
        UInt64 FfmpegStreamInfoTransportSeekDistanceBytes;
        String NativeStartupSeekTransportProvider;
        Boolean NativeStartupSeekTransportCallEvidenceAvailable;
        UInt64 NativeStartupSeekTransportReadCalls;
        UInt64 NativeStartupSeekTransportSeekCalls;
        Double NativeStartupSeekTransportReadWaitMs;
        Double NativeStartupSeekTransportSeekWaitMs;
        UInt64 NativeStartupSeekTransportSeekDistanceBytes;
        String NativeFirstFrameTransportProvider;
        Boolean NativeFirstFrameTransportCallEvidenceAvailable;
        UInt64 NativeFirstFrameTransportReadCalls;
        UInt64 NativeFirstFrameTransportSeekCalls;
        Double NativeFirstFrameTransportReadWaitMs;
        Double NativeFirstFrameTransportSeekWaitMs;
        UInt64 NativeFirstFrameTransportSeekDistanceBytes;
        Double NativeFirstFrameDurationMs;
        Double NativeFirstFrameDemuxReadDurationMs;
        Double NativeFirstFramePresentDurationMs;
        UInt64 NativeFirstFrameDemuxPacketCount;
        UInt64 NativeFirstFrameDemuxBytes;
        Double PlaybackDemuxReadDurationMs;
        UInt64 PlaybackDemuxPacketCount;
        UInt64 PlaybackDemuxBytes;
        String PlaybackTransportProvider;
        Boolean PlaybackTransportCallEvidenceAvailable;
        UInt64 PlaybackTransportReadCalls;
        UInt64 PlaybackTransportSeekCalls;
        Double PlaybackTransportReadWaitMs;
        Double PlaybackTransportSeekWaitMs;
        UInt64 PlaybackTransportSeekDistanceBytes;
        UInt64 ReadErrorCount;
        UInt64 ReadRetryCount;
        UInt64 ReadRecoveryCount;
        UInt32 MaxConsecutiveReadErrors;
        Int32 LastReadErrorCode;
        Int32 FatalReadErrorCode;
        Double LastReadRecoveryDurationMs;
        Int64 ContainerStartTimeTicks;
        Int64 VideoStreamStartTimeTicks;
        Int64 SeekDemuxTargetTicks;
        Int64 FirstPresentedPositionTicks;
        Double SeekLockWaitDurationMs;
        Double SeekExecutionDurationMs;
        Double SeekQuiesceDurationMs;
        Double SeekReplayPreparationDurationMs;
        Double SeekStateResetDurationMs;
        Double SeekMediaRepositionDurationMs;
        Double SeekDependentDecoderFlushDurationMs;
        Double SeekPrerollRenderDurationMs;
        Double SeekWorkerRestartDurationMs;
        Boolean SeekPacketCacheEnabled;
        Boolean SeekPacketCacheHit;
        UInt64 SeekPacketCachePacketCount;
        UInt64 SeekPacketCacheBytes;
        Int64 SeekPacketCacheWindowDurationTicks;
        String SeekFallbackReason;
        Double RenderIntervalMsP05;
        Double RenderIntervalMsP50;
        Double RenderIntervalMsP95;
        Double RenderIntervalMsP99;
        Double MinFrameGapMs;
        Double MaxFrameGapMs;
        UInt64 RenderIntervalSampleCount;
        UInt64 RenderIntervalOverExpected2MsCount;
        UInt64 RenderIntervalOverExpected4MsCount;
        UInt64 RenderIntervalUnderExpected2MsCount;
        UInt64 RenderIntervalUnderExpected4MsCount;
        UInt64 RenderIntervalAfterAudioAheadWaitSampleCount;
        Double RenderIntervalAfterAudioAheadWaitMsP95;
        Double RenderIntervalAfterAudioAheadWaitMsP99;
        Double RenderIntervalAfterAudioAheadWaitMsMax;
        UInt64 AudioAheadWaitEndToPresentSampleCount;
        Double AudioAheadWaitEndToPresentMsP50;
        Double AudioAheadWaitEndToPresentMsP95;
        Double AudioAheadWaitEndToPresentMsP99;
        Double AudioAheadWaitEndToPresentMsMax;
        UInt64 RenderIntervalAfterNonAudioWaitSampleCount;
        Double RenderIntervalAfterNonAudioWaitMsP95;
        Double RenderIntervalAfterNonAudioWaitMsP99;
        Double RenderIntervalAfterNonAudioWaitMsMax;
        Double PresentDurationMsP50;
        Double PresentDurationMsP95;
        Double PresentDurationMsP99;
        Double PresentDurationMsMax;
        Double VideoDecodeDurationMsP50;
        Double VideoDecodeDurationMsP95;
        Double VideoDecodeDurationMsP99;
        Double VideoDecodeDurationMsMax;
        String VideoDecodeDeviceMode;
        String VideoDecodeSynchronizationMode;
        Boolean VideoDecodeWorkerActive;
        UInt64 VideoDecodeQueueCapacity;
        UInt64 VideoDecodeQueueMaxDepth;
        UInt64 VideoDecodeQueueProducerWaitCount;
        UInt64 VideoDecoderSendPacketEagainCount;
        UInt64 VideoDecoderDoubleEagainRetryCount;
        UInt64 VideoDecoderDoubleEagainRecoveryCount;
        UInt64 VideoDecoderDoubleEagainExhaustedCount;
        Double VideoDecodePacketReadDurationMsP50;
        Double VideoDecodePacketReadDurationMsP95;
        Double VideoDecodeSendPacketDurationMsP50;
        Double VideoDecodeSendPacketDurationMsP95;
        Double VideoDecodeReceiveFrameDurationMsP50;
        Double VideoDecodeReceiveFrameDurationMsP95;
        Double VideoDecodeFrameMaterializeDurationMsP50;
        Double VideoDecodeFrameMaterializeDurationMsP95;
        Double VideoRenderDurationMsP50;
        Double VideoRenderDurationMsP95;
        Double VideoRenderDurationMsP99;
        Double VideoRenderDurationMsMax;
        UInt64 VideoRenderDirectCopyFrameCount;
        UInt64 VideoRenderVideoProcessorFrameCount;
        UInt64 VideoRenderBgraFrameCount;
        UInt64 VideoRenderPostProcessFrameCount;
        UInt64 VideoProcessorSetupCpuSampleCount;
        Double VideoProcessorSetupCpuDurationMsP50;
        Double VideoProcessorSetupCpuDurationMsP95;
        Double VideoProcessorSetupCpuDurationMsP99;
        Double VideoProcessorSetupCpuDurationMsMax;
        UInt64 VideoProcessorViewTargetCpuSampleCount;
        Double VideoProcessorViewTargetCpuDurationMsP50;
        Double VideoProcessorViewTargetCpuDurationMsP95;
        Double VideoProcessorViewTargetCpuDurationMsP99;
        Double VideoProcessorViewTargetCpuDurationMsMax;
        UInt64 VideoProcessorClearCpuSampleCount;
        Double VideoProcessorClearCpuDurationMsP50;
        Double VideoProcessorClearCpuDurationMsP95;
        Double VideoProcessorClearCpuDurationMsP99;
        Double VideoProcessorClearCpuDurationMsMax;
        UInt64 VideoProcessorBltCpuSampleCount;
        Double VideoProcessorBltCpuDurationMsP50;
        Double VideoProcessorBltCpuDurationMsP95;
        Double VideoProcessorBltCpuDurationMsP99;
        Double VideoProcessorBltCpuDurationMsMax;
        UInt64 VideoProcessorPostProcessCpuSampleCount;
        Double VideoProcessorPostProcessCpuDurationMsP50;
        Double VideoProcessorPostProcessCpuDurationMsP95;
        Double VideoProcessorPostProcessCpuDurationMsP99;
        Double VideoProcessorPostProcessCpuDurationMsMax;
        Double AudioAheadWaitDurationMsP50;
        Double AudioAheadWaitDurationMsP95;
        Double AudioAheadWaitDurationMsP99;
        Double AudioAheadWaitDurationMsMax;
        Double AudioAheadWaitTargetMsP50;
        Double AudioAheadWaitTargetMsP95;
        Double AudioAheadWaitTargetMsP99;
        Double AudioAheadWaitTargetMsMax;
        Double AudioAheadWaitOversleepMsP50;
        Double AudioAheadWaitOversleepMsP95;
        Double AudioAheadWaitOversleepMsP99;
        Double AudioAheadWaitOversleepMsMax;
        Double AudioAheadWaitFinalDeltaAbsMsP50;
        Double AudioAheadWaitFinalDeltaAbsMsP95;
        Double AudioAheadWaitFinalDeltaAbsMsP99;
        Double AudioAheadWaitFinalDeltaAbsMsMax;
        UInt64 AudioAheadWaitEpisodeCount;
        Double AudioAheadWaitPassesPerEpisodeP50;
        Double AudioAheadWaitPassesPerEpisodeP95;
        Double AudioAheadWaitPassesPerEpisodeP99;
        Double AudioAheadWaitPassesPerEpisodeMax;
        Double AudioAheadWaitPassDurationMsP50;
        Double AudioAheadWaitPassDurationMsP95;
        Double AudioAheadWaitPassDurationMsP99;
        Double AudioAheadWaitPassDurationMsMax;
        Double AudioAheadWaitPassTargetMsP50;
        Double AudioAheadWaitPassTargetMsP95;
        Double AudioAheadWaitPassTargetMsP99;
        Double AudioAheadWaitPassTargetMsMax;
        Double AudioAheadWaitPassOversleepMsP50;
        Double AudioAheadWaitPassOversleepMsP95;
        Double AudioAheadWaitPassOversleepMsP99;
        Double AudioAheadWaitPassOversleepMsMax;
        Double FramePacingSourceFrameRate;
        Double LateFrameDropToleranceMs;
        Double AudioVideoDriftMsP50;
        Double AudioVideoDriftMsP95;
        Double AudioVideoDriftMsP99;
        Double AudioVideoDriftMsMax;
        String LastInteractionScenario;
        UInt64 LastInteractionSequence;
        Double LastInteractionLockWaitDurationMs;
        Double LastInteractionExecutionDurationMs;
        Double LastInteractionQuiesceDurationMs;
        Double LastInteractionSeekDurationMs;
        Double LastInteractionDecoderOpenDurationMs;
        Double LastInteractionRendererOpenDurationMs;
        Boolean LastInteractionPacketCacheHit;
        Boolean LastInteractionPacketCacheEnabled;
        UInt64 LastInteractionPacketCachePacketCount;
        UInt64 LastInteractionPacketCacheBytes;
        Int64 LastInteractionPacketCacheWindowDurationTicks;
    }

    delegate void NativePlaybackStateChangedHandler(NativePlaybackState state, String message);

    runtimeclass NativePlaybackEngine
    {
        NativePlaybackEngine();
        event NativePlaybackStateChangedHandler StateChanged;
        void AttachSurface(Windows.UI.Xaml.Controls.SwapChainPanel panel);
        Int64 CurrentPositionTicks();
        NativePlaybackStatus DisplayStatus();
        NativePlaybackQualityMetrics QualityMetrics();
        Windows.Foundation.IAsyncAction OpenAsync(NativePlaybackOpenRequest request);
        Windows.Foundation.IAsyncAction PauseAsync();
        Windows.Foundation.IAsyncAction ResumeAsync();
        Windows.Foundation.IAsyncAction SeekAsync(Int64 positionTicks);
        Windows.Foundation.IAsyncAction StopAsync();
        Windows.Foundation.IAsyncAction SwitchAudioStreamAsync(Int32 audioStreamIndex);
        Windows.Foundation.IAsyncAction SwitchSubtitleStreamAsync(Int32 subtitleStreamIndex);
        Windows.Foundation.IAsyncAction DisableSubtitlesAsync();
    }
}
