namespace NoiraPlayer.Native
{
    enum NativePlaybackState
    {
        NativePlaybackState_Stopped = 0,
        NativePlaybackState_Opening = 1,
        NativePlaybackState_Buffering = 2,
        NativePlaybackState_Playing = 3,
        NativePlaybackState_Paused = 4,
        NativePlaybackState_Failed = 5
    };

    enum NativeHdrStatus
    {
        NativeHdrStatus_Unknown = 0,
        NativeHdrStatus_Unsupported = 1,
        NativeHdrStatus_Off = 2,
        NativeHdrStatus_On = 3,
        NativeHdrStatus_Failed = 4
    };

    runtimeclass NativePlaybackOpenRequest
    {
        NativePlaybackOpenRequest();
        String ItemId;
        String MediaSourceId;
        String DirectStreamUrl;
        Int64 StartPositionTicks;
        Int32 AudioStreamIndex;
        Boolean HasAudioStreamIndex;
        Int32 SubtitleStreamIndex;
        Boolean HasSubtitleStreamIndex;
        Double VideoFrameRate;
    }

    runtimeclass NativePlaybackStatus
    {
        NativePlaybackStatus();
        NativeHdrStatus HdrStatus;
        Boolean IsHdrDisplayAvailable;
        Boolean IsHdrOutputActive;
        Double RefreshRateHz;
        String Message;
        String SwapChainFormat;
        String SwapChainColorSpace;
        Boolean IsTenBitSwapChain;
        Boolean IsVideoProcessorColorSpaceValidated;
        String VideoProcessorInputColorSpace;
        String VideoProcessorOutputColorSpace;
        String VideoProcessorConversionStatus;
    }

    runtimeclass NativePlaybackQualityMetrics
    {
        NativePlaybackQualityMetrics();
        UInt64 RenderPasses;
        UInt64 DecodedVideoFrames;
        UInt64 HardwareDecodedVideoFrames;
        UInt64 SoftwareDecodedVideoFrames;
        UInt64 RenderedVideoFrames;
        UInt64 SubmittedAudioFrames;
        Int32 SelectedAudioStreamIndex;
        UInt64 SubtitleDecodedCueCount;
        UInt64 SubtitleCueRenderCount;
        Int32 SelectedSubtitleStreamIndex;
        UInt64 DroppedVideoFrames;
        UInt64 SeekPrerollDroppedFrames;
        UInt64 VideoAheadWaitCount;
        UInt64 AudioAheadWaitCount;
        UInt64 VideoClockWaitCount;
        UInt64 VideoStarvedPasses;
        UInt64 AudioStarvedPasses;
        UInt64 QueuedAudioBuffers;
        Int64 AudioClockTicks;
        Int64 VideoPositionTicks;
        Double NativeGraphOpenDurationMs;
        Double FfmpegOpenInputDurationMs;
        Double FfmpegStreamInfoDurationMs;
        Double NativeStartupSeekDurationMs;
        Double NativeFirstFrameDurationMs;
        Int64 ContainerStartTimeTicks;
        Int64 VideoStreamStartTimeTicks;
        Int64 SeekDemuxTargetTicks;
        Int64 FirstPresentedPositionTicks;
        Double RenderIntervalMsP05;
        Double RenderIntervalMsP50;
        Double RenderIntervalMsP95;
        Double RenderIntervalMsP99;
        Double MinFrameGapMs;
        Double MaxFrameGapMs;
        UInt64 RenderIntervalSampleCount;
        UInt64 RenderIntervalOverExpected2MsCount;
        UInt64 RenderIntervalOverExpected4MsCount;
        UInt64 RenderIntervalUnderExpected2MsCount;
        UInt64 RenderIntervalUnderExpected4MsCount;
        UInt64 RenderIntervalAfterAudioAheadWaitSampleCount;
        Double RenderIntervalAfterAudioAheadWaitMsP95;
        Double RenderIntervalAfterAudioAheadWaitMsP99;
        Double RenderIntervalAfterAudioAheadWaitMsMax;
        UInt64 AudioAheadWaitEndToPresentSampleCount;
        Double AudioAheadWaitEndToPresentMsP50;
        Double AudioAheadWaitEndToPresentMsP95;
        Double AudioAheadWaitEndToPresentMsP99;
        Double AudioAheadWaitEndToPresentMsMax;
        UInt64 RenderIntervalAfterNonAudioWaitSampleCount;
        Double RenderIntervalAfterNonAudioWaitMsP95;
        Double RenderIntervalAfterNonAudioWaitMsP99;
        Double RenderIntervalAfterNonAudioWaitMsMax;
        Double PresentDurationMsP50;
        Double PresentDurationMsP95;
        Double PresentDurationMsP99;
        Double PresentDurationMsMax;
        Double AudioAheadWaitDurationMsP50;
        Double AudioAheadWaitDurationMsP95;
        Double AudioAheadWaitDurationMsP99;
        Double AudioAheadWaitDurationMsMax;
        Double AudioAheadWaitTargetMsP50;
        Double AudioAheadWaitTargetMsP95;
        Double AudioAheadWaitTargetMsP99;
        Double AudioAheadWaitTargetMsMax;
        Double AudioAheadWaitOversleepMsP50;
        Double AudioAheadWaitOversleepMsP95;
        Double AudioAheadWaitOversleepMsP99;
        Double AudioAheadWaitOversleepMsMax;
        Double AudioAheadWaitFinalDeltaAbsMsP50;
        Double AudioAheadWaitFinalDeltaAbsMsP95;
        Double AudioAheadWaitFinalDeltaAbsMsP99;
        Double AudioAheadWaitFinalDeltaAbsMsMax;
        UInt64 AudioAheadWaitEpisodeCount;
        Double AudioAheadWaitPassesPerEpisodeP50;
        Double AudioAheadWaitPassesPerEpisodeP95;
        Double AudioAheadWaitPassesPerEpisodeP99;
        Double AudioAheadWaitPassesPerEpisodeMax;
        Double AudioAheadWaitPassDurationMsP50;
        Double AudioAheadWaitPassDurationMsP95;
        Double AudioAheadWaitPassDurationMsP99;
        Double AudioAheadWaitPassDurationMsMax;
        Double AudioAheadWaitPassTargetMsP50;
        Double AudioAheadWaitPassTargetMsP95;
        Double AudioAheadWaitPassTargetMsP99;
        Double AudioAheadWaitPassTargetMsMax;
        Double AudioAheadWaitPassOversleepMsP50;
        Double AudioAheadWaitPassOversleepMsP95;
        Double AudioAheadWaitPassOversleepMsP99;
        Double AudioAheadWaitPassOversleepMsMax;
        Double FramePacingSourceFrameRate;
        Double LateFrameDropToleranceMs;
        Double AudioVideoDriftMsP50;
        Double AudioVideoDriftMsP95;
        Double AudioVideoDriftMsP99;
        Double AudioVideoDriftMsMax;
        String LastInteractionScenario;
        UInt64 LastInteractionSequence;
        Double LastInteractionLockWaitDurationMs;
        Double LastInteractionExecutionDurationMs;
        Double LastInteractionQuiesceDurationMs;
        Double LastInteractionSeekDurationMs;
        Double LastInteractionDecoderOpenDurationMs;
        Double LastInteractionRendererOpenDurationMs;
        Boolean LastInteractionPacketCacheHit;
        Boolean LastInteractionPacketCacheEnabled;
        UInt64 LastInteractionPacketCachePacketCount;
        UInt64 LastInteractionPacketCacheBytes;
        Int64 LastInteractionPacketCacheWindowDurationTicks;
    }

    delegate void NativePlaybackStateChangedHandler(NativePlaybackState state, String message);

    runtimeclass NativePlaybackEngine
    {
        NativePlaybackEngine();
        event NativePlaybackStateChangedHandler StateChanged;
        void AttachSurface(Windows.UI.Xaml.Controls.SwapChainPanel panel);
        Int64 CurrentPositionTicks();
        NativePlaybackStatus DisplayStatus();
        NativePlaybackQualityMetrics QualityMetrics();
        Windows.Foundation.IAsyncAction OpenAsync(NativePlaybackOpenRequest request);
        Windows.Foundation.IAsyncAction PauseAsync();
        Windows.Foundation.IAsyncAction ResumeAsync();
        Windows.Foundation.IAsyncAction SeekAsync(Int64 positionTicks);
        Windows.Foundation.IAsyncAction StopAsync();
        Windows.Foundation.IAsyncAction SwitchAudioStreamAsync(Int32 audioStreamIndex);
        Windows.Foundation.IAsyncAction SwitchSubtitleStreamAsync(Int32 subtitleStreamIndex);
        Windows.Foundation.IAsyncAction DisableSubtitlesAsync();
    }
}
