#include <cassert>

#include <chrono>

#include "Media/PlaybackQualityMetrics.h"

using winrt::NoiraPlayer::Native::implementation::PlaybackQualityMetrics;
using winrt::NoiraPlayer::Native::implementation::PlaybackQualityMetricsSnapshot;
using winrt::NoiraPlayer::Native::implementation::PlaybackPresentationIntervalTracker;

int main()
{
    PlaybackPresentationIntervalTracker intervalTracker;
    const auto firstFrameAt = std::chrono::steady_clock::time_point(std::chrono::milliseconds(100));
    const auto secondFrameAt = firstFrameAt + std::chrono::milliseconds(42);
    assert(!intervalTracker.Observe(firstFrameAt).has_value());
    assert(intervalTracker.Observe(secondFrameAt).value() == 42.0);
    intervalTracker.BreakContinuity();
    const auto resumedFirstFrameAt = secondFrameAt + std::chrono::seconds(10);
    assert(!intervalTracker.Observe(resumedFirstFrameAt).has_value());
    assert(intervalTracker.Observe(resumedFirstFrameAt + std::chrono::milliseconds(42)).value() == 42.0);

    PlaybackQualityMetrics metrics;
    metrics.RecordRenderIntervalMs(10.0);
    metrics.RecordRenderIntervalMs(41.0);
    metrics.RecordRenderIntervalMs(42.0);
    metrics.RecordRenderIntervalMs(100.0);
    metrics.RecordRenderIntervalAfterAudioAheadWaitMs(39.0);
    metrics.RecordRenderIntervalAfterAudioAheadWaitMs(43.0);
    metrics.RecordAudioAheadWaitEndToPresentMs(2.0);
    metrics.RecordAudioAheadWaitEndToPresentMs(7.0);
    metrics.RecordAudioAheadWaitEndToPresentMs(14.0);
    metrics.RecordRenderIntervalAfterNonAudioWaitMs(26.0);
    metrics.RecordRenderIntervalAfterNonAudioWaitMs(34.0);
    metrics.RecordPresentDurationMs(2.0);
    metrics.RecordPresentDurationMs(17.0);
    metrics.RecordPresentDurationMs(34.0);
    metrics.RecordAudioAheadWaitMs(4.0, 1.0, 3.0, 100.0, 1);
    metrics.RecordAudioAheadWaitMs(12.0, 3.0, 9.0, 80.0, 2);
    metrics.RecordAudioAheadWaitMs(24.0, 8.0, 16.0, 50.0, 3);
    metrics.RecordAudioAheadWaitPassMs(5.0, 4.0);
    metrics.RecordAudioAheadWaitPassMs(11.0, 6.0);
    metrics.RecordAudioAheadWaitPassMs(20.0, 8.0);

    PlaybackQualityMetrics episodeMetrics;
    auto episodeOversleepMs = episodeMetrics.RecordAudioAheadWaitPassMs(5.0, 10.0);
    episodeOversleepMs += episodeMetrics.RecordAudioAheadWaitPassMs(7.0, 5.0);
    assert(episodeOversleepMs == 2.0);

    PlaybackQualityMetrics explicitOversleepMetrics;
    explicitOversleepMetrics.RecordAudioAheadWaitMs(20.0, 10.0, 7.0, 0.0, 1);
    assert(explicitOversleepMetrics.Snapshot().AudioAheadWaitOversleepMsMax == 7.0);
    metrics.RecordAudioVideoDriftTicks(200000);
    metrics.RecordAudioVideoDriftTicks(-400000);

    metrics.RenderPasses = 10;
    metrics.DecodedVideoFrames = 4;
    metrics.HardwareDecodedVideoFrames = 3;
    metrics.SoftwareDecodedVideoFrames = 1;
    metrics.RenderedVideoFrames = 3;
    metrics.DroppedVideoFrames = 1;
    metrics.VideoAheadWaitCount = 7;
    metrics.AudioAheadWaitCount = 5;
    metrics.VideoClockWaitCount = 2;
    metrics.VideoStarvedPasses = 2;
    metrics.AudioStarvedPasses = 1;
    metrics.AudioClockTicks = 2'000'000;
    metrics.VideoPositionTicks = 1'800'000;
    metrics.NativeGraphOpenDurationMs = 5000.0;
    metrics.FfmpegOpenInputDurationMs = 4000.0;
    metrics.FfmpegStreamInfoDurationMs = 500.0;
    metrics.NativeStartupSeekDurationMs = 125.0;
    metrics.NativeFirstFrameDurationMs = 100.0;
    metrics.NativeFirstFrameDemuxReadDurationMs = 60.0;
    metrics.NativeFirstFramePresentDurationMs = 5.0;
    metrics.NativeFirstFrameDemuxPacketCount = 200;
    metrics.NativeFirstFrameDemuxBytes = 1'000'000;
    metrics.ContainerStartTimeTicks = 1'400'000;
    metrics.VideoStreamStartTimeTicks = 1'421'333;
    metrics.SeekDemuxTargetTicks = 24'000'000;
    metrics.FirstPresentedPositionTicks = 10'750'000;
    metrics.FramePacingSourceFrameRate = 60.0;
    metrics.LateFrameDropToleranceMs = 41.6667;

    PlaybackQualityMetricsSnapshot snapshot = metrics.Snapshot();

    assert(snapshot.RenderPasses == 10);
    assert(snapshot.DecodedVideoFrames == 4);
    assert(snapshot.HardwareDecodedVideoFrames == 3);
    assert(snapshot.SoftwareDecodedVideoFrames == 1);
    assert(snapshot.RenderedVideoFrames == 3);
    assert(snapshot.DroppedVideoFrames == 1);
    assert(snapshot.VideoAheadWaitCount == 7);
    assert(snapshot.AudioAheadWaitCount == 5);
    assert(snapshot.VideoClockWaitCount == 2);
    assert(snapshot.VideoStarvedPasses == 2);
    assert(snapshot.AudioStarvedPasses == 1);
    assert(snapshot.RenderIntervalMsP50 >= 41.0);
    assert(snapshot.RenderIntervalMsP95 >= 100.0);
    assert(snapshot.MaxFrameGapMs == 100.0);
    assert(snapshot.RenderIntervalMsP05 <= 10.0);
    assert(snapshot.MinFrameGapMs == 10.0);
    assert(snapshot.RenderIntervalSampleCount == 4);
    assert(snapshot.RenderIntervalOverExpected2MsCount == 3);
    assert(snapshot.RenderIntervalOverExpected4MsCount == 3);
    assert(snapshot.RenderIntervalUnderExpected2MsCount == 1);
    assert(snapshot.RenderIntervalUnderExpected4MsCount == 1);
    assert(snapshot.RenderIntervalAfterAudioAheadWaitSampleCount == 2);
    assert(snapshot.RenderIntervalAfterAudioAheadWaitMsP95 >= 43.0);
    assert(snapshot.RenderIntervalAfterAudioAheadWaitMsMax == 43.0);
    assert(snapshot.AudioAheadWaitEndToPresentSampleCount == 3);
    assert(snapshot.AudioAheadWaitEndToPresentMsP50 >= 7.0);
    assert(snapshot.AudioAheadWaitEndToPresentMsP95 >= 14.0);
    assert(snapshot.AudioAheadWaitEndToPresentMsP99 >= 14.0);
    assert(snapshot.AudioAheadWaitEndToPresentMsMax == 14.0);
    assert(snapshot.RenderIntervalAfterNonAudioWaitSampleCount == 2);
    assert(snapshot.RenderIntervalAfterNonAudioWaitMsP95 >= 34.0);
    assert(snapshot.RenderIntervalAfterNonAudioWaitMsMax == 34.0);
    assert(snapshot.PresentDurationMsP50 >= 2.0);
    assert(snapshot.PresentDurationMsP95 >= 34.0);
    assert(snapshot.PresentDurationMsMax == 34.0);
    assert(snapshot.AudioAheadWaitDurationMsP50 >= 4.0);
    assert(snapshot.AudioAheadWaitDurationMsP95 >= 24.0);
    assert(snapshot.AudioAheadWaitDurationMsMax == 24.0);
    assert(snapshot.AudioAheadWaitTargetMsP50 >= 1.0);
    assert(snapshot.AudioAheadWaitTargetMsP95 >= 8.0);
    assert(snapshot.AudioAheadWaitTargetMsMax == 8.0);
    assert(snapshot.AudioAheadWaitOversleepMsP50 >= 3.0);
    assert(snapshot.AudioAheadWaitOversleepMsP95 >= 16.0);
    assert(snapshot.AudioAheadWaitOversleepMsMax == 16.0);
    assert(snapshot.AudioAheadWaitFinalDeltaAbsMsP50 >= 50.0);
    assert(snapshot.AudioAheadWaitFinalDeltaAbsMsP95 >= 100.0);
    assert(snapshot.AudioAheadWaitFinalDeltaAbsMsMax == 100.0);
    assert(snapshot.AudioAheadWaitEpisodeCount == 3);
    assert(snapshot.AudioAheadWaitPassesPerEpisodeP50 >= 1.0);
    assert(snapshot.AudioAheadWaitPassesPerEpisodeP95 >= 3.0);
    assert(snapshot.AudioAheadWaitPassesPerEpisodeMax == 3.0);
    assert(snapshot.AudioAheadWaitPassDurationMsP50 >= 5.0);
    assert(snapshot.AudioAheadWaitPassDurationMsP95 >= 20.0);
    assert(snapshot.AudioAheadWaitPassDurationMsMax == 20.0);
    assert(snapshot.AudioAheadWaitPassTargetMsP50 >= 4.0);
    assert(snapshot.AudioAheadWaitPassTargetMsP95 >= 8.0);
    assert(snapshot.AudioAheadWaitPassTargetMsMax == 8.0);
    assert(snapshot.AudioAheadWaitPassOversleepMsP50 >= 1.0);
    assert(snapshot.AudioAheadWaitPassOversleepMsP95 >= 12.0);
    assert(snapshot.AudioAheadWaitPassOversleepMsMax == 12.0);
    assert(snapshot.AudioVideoDriftMsP95 >= 40.0);
    assert(snapshot.AudioVideoDriftMsMax >= 40.0);
    assert(snapshot.AudioClockTicks == 2'000'000);
    assert(snapshot.VideoPositionTicks == 1'800'000);
    assert(snapshot.NativeGraphOpenDurationMs == 5000.0);
    assert(snapshot.FfmpegOpenInputDurationMs == 4000.0);
    assert(snapshot.FfmpegStreamInfoDurationMs == 500.0);
    assert(snapshot.NativeStartupSeekDurationMs == 125.0);
    assert(snapshot.NativeFirstFrameDurationMs == 100.0);
    assert(snapshot.NativeFirstFrameDemuxReadDurationMs == 60.0);
    assert(snapshot.NativeFirstFramePresentDurationMs == 5.0);
    assert(snapshot.NativeFirstFrameDemuxPacketCount == 200);
    assert(snapshot.NativeFirstFrameDemuxBytes == 1'000'000);
    assert(snapshot.ContainerStartTimeTicks == 1'400'000);
    assert(snapshot.VideoStreamStartTimeTicks == 1'421'333);
    assert(snapshot.SeekDemuxTargetTicks == 24'000'000);
    assert(snapshot.FirstPresentedPositionTicks == 10'750'000);
    assert(snapshot.FramePacingSourceFrameRate == 60.0);
    assert(snapshot.LateFrameDropToleranceMs > 41.0);

    metrics.ResetRuntimeSamplesPreservingOpenTiming();
    snapshot = metrics.Snapshot();
    assert(snapshot.RenderPasses == 0);
    assert(snapshot.RenderedVideoFrames == 0);
    assert(snapshot.NativeGraphOpenDurationMs == 5000.0);
    assert(snapshot.FfmpegOpenInputDurationMs == 4000.0);
    assert(snapshot.FfmpegStreamInfoDurationMs == 500.0);
    assert(snapshot.NativeStartupSeekDurationMs == 125.0);
    assert(snapshot.NativeFirstFrameDurationMs == 100.0);
    assert(snapshot.NativeFirstFrameDemuxReadDurationMs == 60.0);
    assert(snapshot.NativeFirstFramePresentDurationMs == 5.0);
    assert(snapshot.NativeFirstFrameDemuxPacketCount == 200);
    assert(snapshot.NativeFirstFrameDemuxBytes == 1'000'000);
    assert(snapshot.ContainerStartTimeTicks == 1'400'000);
    assert(snapshot.VideoStreamStartTimeTicks == 1'421'333);
    assert(snapshot.SeekDemuxTargetTicks == -1);
    assert(snapshot.FirstPresentedPositionTicks == -1);

    metrics.Reset();
    snapshot = metrics.Snapshot();
    assert(snapshot.RenderPasses == 0);
    assert(snapshot.HardwareDecodedVideoFrames == 0);
    assert(snapshot.SoftwareDecodedVideoFrames == 0);
    assert(snapshot.VideoAheadWaitCount == 0);
    assert(snapshot.AudioAheadWaitCount == 0);
    assert(snapshot.VideoClockWaitCount == 0);
    assert(snapshot.MaxFrameGapMs == 0.0);
    assert(snapshot.MinFrameGapMs == 0.0);
    assert(snapshot.RenderIntervalSampleCount == 0);
    assert(snapshot.RenderIntervalOverExpected2MsCount == 0);
    assert(snapshot.RenderIntervalOverExpected4MsCount == 0);
    assert(snapshot.RenderIntervalUnderExpected2MsCount == 0);
    assert(snapshot.RenderIntervalUnderExpected4MsCount == 0);
    assert(snapshot.RenderIntervalAfterAudioAheadWaitSampleCount == 0);
    assert(snapshot.RenderIntervalAfterAudioAheadWaitMsMax == 0.0);
    assert(snapshot.AudioAheadWaitEndToPresentSampleCount == 0);
    assert(snapshot.AudioAheadWaitEndToPresentMsMax == 0.0);
    assert(snapshot.RenderIntervalAfterNonAudioWaitSampleCount == 0);
    assert(snapshot.RenderIntervalAfterNonAudioWaitMsMax == 0.0);
    assert(snapshot.PresentDurationMsMax == 0.0);
    assert(snapshot.AudioAheadWaitDurationMsMax == 0.0);
    assert(snapshot.AudioAheadWaitTargetMsMax == 0.0);
    assert(snapshot.AudioAheadWaitOversleepMsMax == 0.0);
    assert(snapshot.AudioAheadWaitFinalDeltaAbsMsMax == 0.0);
    assert(snapshot.AudioAheadWaitEpisodeCount == 0);
    assert(snapshot.AudioAheadWaitPassesPerEpisodeMax == 0.0);
    assert(snapshot.AudioAheadWaitPassDurationMsMax == 0.0);
    assert(snapshot.AudioAheadWaitPassTargetMsMax == 0.0);
    assert(snapshot.AudioAheadWaitPassOversleepMsMax == 0.0);
    assert(snapshot.AudioVideoDriftMsMax == 0.0);
    assert(snapshot.FramePacingSourceFrameRate == 0.0);
    assert(snapshot.LateFrameDropToleranceMs == 0.0);
    assert(snapshot.NativeGraphOpenDurationMs == 0.0);
    assert(snapshot.FfmpegOpenInputDurationMs == 0.0);
    assert(snapshot.FfmpegStreamInfoDurationMs == 0.0);
    assert(snapshot.NativeStartupSeekDurationMs == 0.0);
    assert(snapshot.NativeFirstFrameDurationMs == 0.0);
    assert(snapshot.NativeFirstFrameDemuxReadDurationMs == 0.0);
    assert(snapshot.NativeFirstFramePresentDurationMs == 0.0);
    assert(snapshot.NativeFirstFrameDemuxPacketCount == 0);
    assert(snapshot.NativeFirstFrameDemuxBytes == 0);

    return 0;
}
